/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as authenticatedLayoutImport } from './routes/(authenticated)/_layout'
import { Route as authenticatedLayoutSIndexImport } from './routes/(authenticated)/_layout/s/index'
import { Route as authenticatedLayoutCIndexImport } from './routes/(authenticated)/_layout/c/index'
import { Route as authenticatedLayoutAIndexImport } from './routes/(authenticated)/_layout/a/index'
import { Route as authenticatedLayoutSProfileImport } from './routes/(authenticated)/_layout/s/profile'
import { Route as authenticatedLayoutSOjtRequirementsImport } from './routes/(authenticated)/_layout/s/ojt-requirements'
import { Route as authenticatedLayoutSLinksImport } from './routes/(authenticated)/_layout/s/links'
import { Route as authenticatedLayoutSCompanySearchImport } from './routes/(authenticated)/_layout/s/company-search'

// Create Virtual Routes

const authenticatedImport = createFileRoute('/(authenticated)')()

// Create/Update Routes

const authenticatedRoute = authenticatedImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const authenticatedLayoutRoute = authenticatedLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => authenticatedRoute,
} as any)

const authenticatedLayoutSIndexRoute = authenticatedLayoutSIndexImport.update({
  id: '/s/',
  path: '/s/',
  getParentRoute: () => authenticatedLayoutRoute,
} as any)

const authenticatedLayoutCIndexRoute = authenticatedLayoutCIndexImport.update({
  id: '/c/',
  path: '/c/',
  getParentRoute: () => authenticatedLayoutRoute,
} as any)

const authenticatedLayoutAIndexRoute = authenticatedLayoutAIndexImport.update({
  id: '/a/',
  path: '/a/',
  getParentRoute: () => authenticatedLayoutRoute,
} as any)

const authenticatedLayoutSProfileRoute =
  authenticatedLayoutSProfileImport.update({
    id: '/s/profile',
    path: '/s/profile',
    getParentRoute: () => authenticatedLayoutRoute,
  } as any)

const authenticatedLayoutSOjtRequirementsRoute =
  authenticatedLayoutSOjtRequirementsImport.update({
    id: '/s/ojt-requirements',
    path: '/s/ojt-requirements',
    getParentRoute: () => authenticatedLayoutRoute,
  } as any)

const authenticatedLayoutSLinksRoute = authenticatedLayoutSLinksImport.update({
  id: '/s/links',
  path: '/s/links',
  getParentRoute: () => authenticatedLayoutRoute,
} as any)

const authenticatedLayoutSCompanySearchRoute =
  authenticatedLayoutSCompanySearchImport.update({
    id: '/s/company-search',
    path: '/s/company-search',
    getParentRoute: () => authenticatedLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedImport
      parentRoute: typeof rootRoute
    }
    '/(authenticated)/_layout': {
      id: '/(authenticated)/_layout'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedLayoutImport
      parentRoute: typeof authenticatedRoute
    }
    '/(authenticated)/_layout/s/company-search': {
      id: '/(authenticated)/_layout/s/company-search'
      path: '/s/company-search'
      fullPath: '/s/company-search'
      preLoaderRoute: typeof authenticatedLayoutSCompanySearchImport
      parentRoute: typeof authenticatedLayoutImport
    }
    '/(authenticated)/_layout/s/links': {
      id: '/(authenticated)/_layout/s/links'
      path: '/s/links'
      fullPath: '/s/links'
      preLoaderRoute: typeof authenticatedLayoutSLinksImport
      parentRoute: typeof authenticatedLayoutImport
    }
    '/(authenticated)/_layout/s/ojt-requirements': {
      id: '/(authenticated)/_layout/s/ojt-requirements'
      path: '/s/ojt-requirements'
      fullPath: '/s/ojt-requirements'
      preLoaderRoute: typeof authenticatedLayoutSOjtRequirementsImport
      parentRoute: typeof authenticatedLayoutImport
    }
    '/(authenticated)/_layout/s/profile': {
      id: '/(authenticated)/_layout/s/profile'
      path: '/s/profile'
      fullPath: '/s/profile'
      preLoaderRoute: typeof authenticatedLayoutSProfileImport
      parentRoute: typeof authenticatedLayoutImport
    }
    '/(authenticated)/_layout/a/': {
      id: '/(authenticated)/_layout/a/'
      path: '/a'
      fullPath: '/a'
      preLoaderRoute: typeof authenticatedLayoutAIndexImport
      parentRoute: typeof authenticatedLayoutImport
    }
    '/(authenticated)/_layout/c/': {
      id: '/(authenticated)/_layout/c/'
      path: '/c'
      fullPath: '/c'
      preLoaderRoute: typeof authenticatedLayoutCIndexImport
      parentRoute: typeof authenticatedLayoutImport
    }
    '/(authenticated)/_layout/s/': {
      id: '/(authenticated)/_layout/s/'
      path: '/s'
      fullPath: '/s'
      preLoaderRoute: typeof authenticatedLayoutSIndexImport
      parentRoute: typeof authenticatedLayoutImport
    }
  }
}

// Create and export the route tree

interface authenticatedLayoutRouteChildren {
  authenticatedLayoutSCompanySearchRoute: typeof authenticatedLayoutSCompanySearchRoute
  authenticatedLayoutSLinksRoute: typeof authenticatedLayoutSLinksRoute
  authenticatedLayoutSOjtRequirementsRoute: typeof authenticatedLayoutSOjtRequirementsRoute
  authenticatedLayoutSProfileRoute: typeof authenticatedLayoutSProfileRoute
  authenticatedLayoutAIndexRoute: typeof authenticatedLayoutAIndexRoute
  authenticatedLayoutCIndexRoute: typeof authenticatedLayoutCIndexRoute
  authenticatedLayoutSIndexRoute: typeof authenticatedLayoutSIndexRoute
}

const authenticatedLayoutRouteChildren: authenticatedLayoutRouteChildren = {
  authenticatedLayoutSCompanySearchRoute:
    authenticatedLayoutSCompanySearchRoute,
  authenticatedLayoutSLinksRoute: authenticatedLayoutSLinksRoute,
  authenticatedLayoutSOjtRequirementsRoute:
    authenticatedLayoutSOjtRequirementsRoute,
  authenticatedLayoutSProfileRoute: authenticatedLayoutSProfileRoute,
  authenticatedLayoutAIndexRoute: authenticatedLayoutAIndexRoute,
  authenticatedLayoutCIndexRoute: authenticatedLayoutCIndexRoute,
  authenticatedLayoutSIndexRoute: authenticatedLayoutSIndexRoute,
}

const authenticatedLayoutRouteWithChildren =
  authenticatedLayoutRoute._addFileChildren(authenticatedLayoutRouteChildren)

interface authenticatedRouteChildren {
  authenticatedLayoutRoute: typeof authenticatedLayoutRouteWithChildren
}

const authenticatedRouteChildren: authenticatedRouteChildren = {
  authenticatedLayoutRoute: authenticatedLayoutRouteWithChildren,
}

const authenticatedRouteWithChildren = authenticatedRoute._addFileChildren(
  authenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof authenticatedLayoutRouteWithChildren
  '/s/company-search': typeof authenticatedLayoutSCompanySearchRoute
  '/s/links': typeof authenticatedLayoutSLinksRoute
  '/s/ojt-requirements': typeof authenticatedLayoutSOjtRequirementsRoute
  '/s/profile': typeof authenticatedLayoutSProfileRoute
  '/a': typeof authenticatedLayoutAIndexRoute
  '/c': typeof authenticatedLayoutCIndexRoute
  '/s': typeof authenticatedLayoutSIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof authenticatedLayoutRouteWithChildren
  '/s/company-search': typeof authenticatedLayoutSCompanySearchRoute
  '/s/links': typeof authenticatedLayoutSLinksRoute
  '/s/ojt-requirements': typeof authenticatedLayoutSOjtRequirementsRoute
  '/s/profile': typeof authenticatedLayoutSProfileRoute
  '/a': typeof authenticatedLayoutAIndexRoute
  '/c': typeof authenticatedLayoutCIndexRoute
  '/s': typeof authenticatedLayoutSIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(authenticated)': typeof authenticatedRouteWithChildren
  '/(authenticated)/_layout': typeof authenticatedLayoutRouteWithChildren
  '/(authenticated)/_layout/s/company-search': typeof authenticatedLayoutSCompanySearchRoute
  '/(authenticated)/_layout/s/links': typeof authenticatedLayoutSLinksRoute
  '/(authenticated)/_layout/s/ojt-requirements': typeof authenticatedLayoutSOjtRequirementsRoute
  '/(authenticated)/_layout/s/profile': typeof authenticatedLayoutSProfileRoute
  '/(authenticated)/_layout/a/': typeof authenticatedLayoutAIndexRoute
  '/(authenticated)/_layout/c/': typeof authenticatedLayoutCIndexRoute
  '/(authenticated)/_layout/s/': typeof authenticatedLayoutSIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/s/company-search'
    | '/s/links'
    | '/s/ojt-requirements'
    | '/s/profile'
    | '/a'
    | '/c'
    | '/s'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/s/company-search'
    | '/s/links'
    | '/s/ojt-requirements'
    | '/s/profile'
    | '/a'
    | '/c'
    | '/s'
  id:
    | '__root__'
    | '/'
    | '/(authenticated)'
    | '/(authenticated)/_layout'
    | '/(authenticated)/_layout/s/company-search'
    | '/(authenticated)/_layout/s/links'
    | '/(authenticated)/_layout/s/ojt-requirements'
    | '/(authenticated)/_layout/s/profile'
    | '/(authenticated)/_layout/a/'
    | '/(authenticated)/_layout/c/'
    | '/(authenticated)/_layout/s/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authenticatedRoute: typeof authenticatedRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authenticatedRoute: authenticatedRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(authenticated)"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(authenticated)": {
      "filePath": "(authenticated)",
      "children": [
        "/(authenticated)/_layout"
      ]
    },
    "/(authenticated)/_layout": {
      "filePath": "(authenticated)/_layout.tsx",
      "parent": "/(authenticated)",
      "children": [
        "/(authenticated)/_layout/s/company-search",
        "/(authenticated)/_layout/s/links",
        "/(authenticated)/_layout/s/ojt-requirements",
        "/(authenticated)/_layout/s/profile",
        "/(authenticated)/_layout/a/",
        "/(authenticated)/_layout/c/",
        "/(authenticated)/_layout/s/"
      ]
    },
    "/(authenticated)/_layout/s/company-search": {
      "filePath": "(authenticated)/_layout/s/company-search.tsx",
      "parent": "/(authenticated)/_layout"
    },
    "/(authenticated)/_layout/s/links": {
      "filePath": "(authenticated)/_layout/s/links.tsx",
      "parent": "/(authenticated)/_layout"
    },
    "/(authenticated)/_layout/s/ojt-requirements": {
      "filePath": "(authenticated)/_layout/s/ojt-requirements.tsx",
      "parent": "/(authenticated)/_layout"
    },
    "/(authenticated)/_layout/s/profile": {
      "filePath": "(authenticated)/_layout/s/profile.tsx",
      "parent": "/(authenticated)/_layout"
    },
    "/(authenticated)/_layout/a/": {
      "filePath": "(authenticated)/_layout/a/index.tsx",
      "parent": "/(authenticated)/_layout"
    },
    "/(authenticated)/_layout/c/": {
      "filePath": "(authenticated)/_layout/c/index.tsx",
      "parent": "/(authenticated)/_layout"
    },
    "/(authenticated)/_layout/s/": {
      "filePath": "(authenticated)/_layout/s/index.tsx",
      "parent": "/(authenticated)/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
