name: ojt-app-dev

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - ojt-app
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports: 
      - 5173:5173
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev -- --host
    depends_on:
      - server
    networks:
      - ojt-app

networks:
  ojt-app:
    driver: bridge
